version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm run build
      - npm install -g @angular/cli@10.0.8
  build:
    commands:
      - echo "Building Angular project..."
     
artifacts:
   files:
     app/build/outputs/apk/app-debug.apk
discard-paths: "yes"

    
