version: 0.2
phases:
  install:
    runtime-versions: 
      android: 29
      nodejs: 12
   pre_build:
    commands:
      - npm install
      - npm install -g react-native-cli
      - echo Pre Build started on `date`
  build:
    commands:
      - echo Build started on `date`
      # - react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      #- cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug

 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*.apk'
discard-paths: "yes"
