version: 0.2
phases:
    build:
        commands:
          - $ANDROID_HOME/tools/bin/sdkmanager "build-tools;27.0.3" "platforms;android-27"
          - sh gradlew assembleDebug
    artifacts:
         files:
             - app/build/outputs/apk/debug/app-debug.apk
             #some other stuff here.








