version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - pwd
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - npm --version
      - react-native link
      - pwd
      
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean
      - ./gradlew assembleRelease
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - /app/build/outputs/apk/release/*.apk
  discard-paths: yes
