version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - npm install
      - echo Pre Build started on `date`
     
  build:
    commands:
      - echo Build started on `date`
      - sudo apt install gradlew
      - react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - cd android
     # - chmod +x gradlew
      - ./gradlew clean
    
      - ./gradlew assembleDebug
      
  
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*.apk'
discard-paths: "yes"    
