version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Testing...
      
      - echo Building...
      
artifacts:
  files:
    - "**/*.apk"
  discard-paths: yes
  base-directory: dist
