version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - npm install
      - echo Pre Build started on `date`
     
  build:
    commands:
      - echo Build started on `date`
      
  
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./build_output/**/*.apk
discard-paths: "yes"    
